apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: eks/aws-load-balancer-controller
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: kube-system
  values:
    - values-dev.yaml

